// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ``` 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASkK1-n2M_EEq2XYXLkb1neLSaJ-8m2gU',
    appId: '1:874568676130:web:dd606b79492e19520e2b7b',
    messagingSenderId: '874568676130',
    projectId: 'app-catalogo-proyecto',
    authDomain: 'app-catalogo-proyecto.firebaseapp.com',
    storageBucket: 'app-catalogo-proyecto.firebasestorage.app',
    measurementId: 'G-NMNQH9433S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXj2y_VAaWG3hu7coVhwqGH17Q9g45FPY',
    appId: '1:874568676130:android:59231444ca27faa90e2b7b',
    messagingSenderId: '874568676130',
    projectId: 'app-catalogo-proyecto',
    storageBucket: 'app-catalogo-proyecto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZeS760RlgsujfIetlRxQ-A2bBuk0pcWE',
    appId: '1:874568676130:ios:626f0f64d003e8570e2b7b',
    messagingSenderId: '874568676130',
    projectId: 'app-catalogo-proyecto',
    storageBucket: 'app-catalogo-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZeS760RlgsujfIetlRxQ-A2bBuk0pcWE',
    appId: '1:874568676130:ios:626f0f64d003e8570e2b7b',
    messagingSenderId: '874568676130',
    projectId: 'app-catalogo-proyecto',
    storageBucket: 'app-catalogo-proyecto.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASkK1-n2M_EEq2XYXLkb1neLSaJ-8m2gU',
    appId: '1:874568676130:web:5af3f5cb9b4b33bf0e2b7b',
    messagingSenderId: '874568676130',
    projectId: 'app-catalogo-proyecto',
    authDomain: 'app-catalogo-proyecto.firebaseapp.com',
    storageBucket: 'app-catalogo-proyecto.firebasestorage.app',
    measurementId: 'G-6795437KG1',
  );
}
